apiVersion: v1
kind: Service
metadata:
  name: osm-api
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: osm-api
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osm-api-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: osm-api
  name: osm-api
spec:
  replicas: 1
  selector:
    matchLabels:
      run: osm-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: osm-api
    spec:
      containers:
      - image: openindoor/osm-api:0.0.0
        name: osm-api
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /data
            name: osm-storage
      volumes:
      - name: osm-storage
        persistentVolumeClaim:
          claimName: osm-api-pvc
